version: '3.4'

services:
  springbootwebapi-db:
    container_name: springbootwebapi-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQLDB_HOST_PORT:$MYSQLDB_CONTAINER_PORT
    volumes:
      - mysqldbvolume:/var/lib/mysql

volumes:
  mysqldbvolume:
