version: '3.4'

services:
  springbootwebapi-db:
    container_name: springbootwebapi-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQLDB_HOST_PORT:$MYSQLDB_CONTAINER_PORT
    volumes:
      - mysqldbvolume:/var/lib/mysql
      
  springbootwebapi-api:
    container_name: springbootwebapi-api
    image: bmassioui/springbootwebapi-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - $SPRING_HOST_PORT:$SPRING_CONTAINER_PORT
    environment:
      - SPRING_DATASOURCE_URL=JDBC:MYSQL://springbootwebapi-db:$MYSQLDB_CONTAINER_PORT/$MYSQL_DATABASE
      - SPRING_DATASOURCE_USERNAME=$MYSQL_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQL_PASSWORD
    links:
      - springbootwebapi-db
    depends_on:
      - springbootwebapi-db

volumes:
  mysqldbvolume:
